# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa93f134717149b5d9bbc14cbe022961e4cd335ccb25790120e6cb7041afdbcd4a4f5f24b3733c1aa8480aa4fecbf21d3cdf3d90f7055057b98f076f802943a1

test:
  secret_key_base: 009415963df29088192061fc4cb44053d0bd99975f97c63ab18696d276adaef77ae0ca79df1a9f1dbd5b64497c4f4d3a3f57041a8d88b2ea4f6a462e701a5bd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
